#!/bin/bash

outputName=out.jpg
recursivelyDir=.

GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

recursively() {
  for file in `find ${recursivelyDir} -name '*.heic'`; do
      heic="${file}"
      dir=$(dirname ${file})
      out=${dir}/${outputName}
      result=`sips --setProperty format jpeg ${heic} --out ${out}`
      echo ${GREEN}${result}${RESET}
  done
}

recursively
